version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: datalagring
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -U postgres -d datalagring
      interval: 1s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
