version: "3"

services:

  server:
    tty: true
    container_name: datalagring_server
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: dev
      DB_HOST: db
      DB_NAME: datalagring
      DB_USERNAME: postgres
      DB_PORT: 5432
      DB_PASSWORD: password
      SERVER_PORT: 8080
    volumes:
      - ./data.sql:/var/task/migrations/20231128095001321-init-up.sql
    
    ports:
      - "8080:8080"
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: datalagring
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -U postgres -d datalagring
      interval: 1s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./migrate-up.sql:/docker-entrypoint-initdb.d/init.sql

